### ISSUE TITLE
涂抹处未被背景纹理填充

### ISSUE THREAD

**Issue by temco** [lxfater/inpaint-web#17]
是我的chrome有什么问题么？
![bag_cleanup](https://github.com/lxfater/inpaint-web/assets/3907950/6ee0eb90-99ef-4548-b9dc-eb5d4771bf1e)

**Comment by lxfater** [comment]
无法判断你的情况，是否后续还有这个问题

**Comment by temco** [comment]
就是在https://inpaintweb.lxfater.com 在线试用场景中出现的，chrome版本是119.0.6045.159，MacOS
Monterey 12.7.1 (21G920)

lxfater ***@***.***> 于2023年11月22日周三 23:32写道：

**Comment by lxfater** [comment]
一直是这个问题吗？

**Comment by temco** [comment]
对，稳定复现的

lxfater ***@***.***> 于2023年11月23日周四 09:56写道：

**Comment by lxfater** [comment]
麻烦试试最新版本，看看是否有这个问题

**Comment by temco** [comment]
的确变好了，但看上去还有水痕，感觉演示视频里的效果要好很多 😅

lxfater ***@***.***> 于2023年11月26日周日 01:30写道：
