### ISSUE TITLE
Editing another region modifies previously inpainted area

### ISSUE THREAD

**Issue by AndranikSargsyan** [lxfater/inpaint-web#33]
When inpainting some region, then trying to edit another region, the region which was previously inpainted also gets modified. This behavior is likely undesirable in most cases and can be considered a bug. In other words, with every edit, mask should be composed from scratch and the image should be the latest edit, while the current approach seems to unite the currently created mask with all previous masks before passing it to the model.

**Comment by lxfater** [comment]
fixed
