### ISSUE TITLE
大佬能做成一键包吗？谢谢~

### ISSUE THREAD

**Issue by aimarxjg** [lxfater/inpaint-web#51]
自从老哥放出这东西第一天开始，我就没能加载成功过那个30MB的模型......

**Comment by lly-ke** [comment]
要开代理, 下载模型用的是huggingface被国内墙了

**Comment by lxfater** [comment]
现在应该有国内的地址，国外的下载不来的话，自动下载国内的。假如你的没有成功，可以通知我。

**Comment by aimarxjg** [comment]
谢谢，谢谢，谢谢

**Comment by liudonghua123** [comment]
I forked this repo, and tried to replace huggingface with hf-mirror, but failed to fetch the models due to cors problems. So I tried to server the models locally. And I am trying to fix some other problems related to onnxruntime-web.
