### ISSUE TITLE
图片无法处理

### ISSUE THREAD

**Issue by yuanhang-dev** [lxfater/inpaint-web#55]
![CleanShot 2023-12-25 at 13 11 24@2x](https://github.com/lxfater/inpaint-web/assets/35065417/6a924c09-957c-40d3-9f29-75ff9a6af53d)
无论是本地端还是网页端，在执行和 demo 相同操作时，均无法实现 demo 的效果，返回的图都是纯黑色

**Comment by lxfater** [comment]
可能是显存爆了还是啥原因，目前没时间解决，试试其他浏览器或者电脑吧！或者使用lama-cleaner

**Comment by yuanhang-dev** [comment]
浏览器问题，Arc 不行，chrome 可以
