### ISSUE TITLE
涂改后，图片分辨率降低很多

### ISSUE THREAD

**Issue by tisfeng** [lxfater/inpaint-web#7]
原图 3528*2232

<img width="1764" alt="fa42ecee447622a0c2dad213ad587175" src="https://github.com/lxfater/inpaint-web/assets/25194972/fd790859-c54b-49f3-9fa3-af216bd938ae">

修改后 1024*647

![fa42ecee447622a0c2dad213ad587175_cleanup](https://github.com/lxfater/inpaint-web/assets/25194972/ee935278-1cf4-406d-b759-b58690fc30d9)

**Comment by lxfater** [comment]
大图片影响性能，后续优化性能后会改进

**Comment by tisfeng** [comment]
以现在设备的分辨率，即使随便截一张图也不只 1024 尺寸，目前这个尺寸限制会让很多图片无法使用。

期待后续性能优化。

**Comment by tisfeng** [comment]
能否够提供一个选项，让用户选择保持原始图片尺寸输出，慢点就慢点，也比图花了好。

**Comment by wangrongding** [comment]
hi~ @lxfater 想和你交个朋友，我也是开源爱好者，这是我的微信 ChicSparrow，可以加个好友嘛~

**Comment by Sanster** [comment]
@lxfater 可以参考 lama-cleaner 的 crop 推理逻辑，裁一块图片出来推理再贴回去：https://github.com/Sanster/lama-cleaner/blob/af00512cf7764fc26080458d3c378dfe4f23c102/lama_cleaner/model/base.py#L84

@tisfeng lama-cleaner 有个在线 demo，没有分辨率限制，可以试试，不过 demo 是 cpu 跑的，会比较慢 https://huggingface.co/spaces/Sanster/Lama-Cleaner-lama

**Comment by lxfater** [comment]
目前里面是论文resize的逻辑，就是现做图形合并的时候比较慢，前端图片绘制的时候没有搞真实分辨率，图片合并慢可以写webgpu shader解决，或者 后处理集成到模型中。

**Comment by lxfater** [comment]
身体有点不好，写不了，只能周六日写，有老哥愿意下场写吗？写之前可以回一个，避免两个人同时写了。

**Comment by tisfeng** [comment]
@Sanster  用 lama-cleaner 试了一下，去字幕效果不错，但有个比较严重的问题，好像会使图片颜色失真，鲜艳度降低较明显 😢

lama-cleaner 改图：
![fa42ecee447622a0c2dad213ad587175_cleanup (2)](https://github.com/lxfater/inpaint-web/assets/25194972/63c646a8-18c5-42b1-92bf-9c19981cbfd8)

原图：
<img width="1764" alt="fa42ecee447622a0c2dad213ad587175" src="https://github.com/lxfater/inpaint-web/assets/25194972/91b7e740-9b68-4544-929d-92407c1b41c4">

**Comment by Sanster** [comment]
@lxfater 嗯，看了下保存的文件，颜色描述文件名称丢了，我看看怎么修 <img width="135" alt="image" src="https://github.com/lxfater/inpaint-web/assets/3998421/7434429f-226c-4842-9a23-43f8003243b9">

**Comment by tisfeng** [comment]
试了一下，最新版好像修复了，图片涂改后，分辨率保持不变 😃

![fa42ecee447622a0c2dad213ad587175_cleanup (3)](https://github.com/lxfater/inpaint-web/assets/25194972/04fff2e2-24b3-460f-8786-4952ad7dcbdc)

**Comment by lxfater** [comment]
是的，但是现在前端代码有性能问题

**Comment by tisfeng** [comment]
赞，目前已经比较好用了 ❤️

另外，希望能优化一下笔刷纹理，去除字幕后，笔刷遗留的马赛克痕迹略感明显，这点 lama-cleaner 处理得更好一些。

**Comment by lxfater** [comment]
> 赞，目前已经比较好用了 ❤️
> 
> 另外，希望能优化一下笔刷纹理，去除字幕后，笔刷遗留的马赛克痕迹略感明显，这点 lama-cleaner 处理得更好一些。

最新版本有着明显的改善

**Comment by tisfeng** [comment]
效果很好，非常棒！

![fa42ecee447622a0c2dad213ad587175_cleanup (4)](https://github.com/lxfater/inpaint-web/assets/25194972/259f7576-d109-4801-ba8f-437ecb918922)
